### ISSUE TITLE
[Content] Add new Research Development Lab group pages

### ISSUE THREAD

**Issue by KarolaKirsanow** [protocol/research-website#234]
### Description
as separate PRs:
- [ ] Add CryptoComputeLab
- [ ] Add CryptoNetLab
- [ ] Add ConsensusLab
- [x] Add IncentiveLab

This includes:
- [x]  selecting temporary streamline icons
- [x] deciding how extant CryptoLab content should be apportioned
- [ ] ordering rollout and opening PRs
- [ ] writing/soliciting group mission statements
- [x] tagging content
- [x] tagging personnel
